# Generated by Django 4.2.7 on 2023-11-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyimages',
            fields=[
                ('keyimageuid', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('patientid', models.CharField(blank=True, max_length=512, null=True)),
                ('studyuid', models.CharField(blank=True, max_length=512, null=True)),
                ('seriename', models.CharField(blank=True, max_length=512, null=True)),
                ('seriesuid', models.CharField(blank=True, max_length=512, null=True)),
                ('ismultiframe', models.BooleanField(blank=True, null=True)),
                ('instanceuid', models.CharField(blank=True, max_length=512, null=True)),
                ('slice', models.IntegerField(blank=True, null=True)),
                ('wadouri', models.CharField(max_length=512)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('isfusion', models.BooleanField(blank=True, null=True)),
                ('backlayer', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'keyimages',
                'indexes': [models.Index(fields=['studyuid'], name='idx_study'), models.Index(fields=['seriesuid'], name='idx_series'), models.Index(fields=['instanceuid'], name='idx_instance')],
            },
        ),
    ]
