# Generated by Django 4.2.7 on 2023-11-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_images_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='keyimages',
            name='idx_series',
        ),
        migrations.RemoveIndex(
            model_name='keyimages',
            name='idx_instance',
        ),
        migrations.AddIndex(
            model_name='keyimages',
            index=models.Index(fields=['patientid'], name='idx_patient_id'),
        ),
    ]
