"""
Django settings for key_images_back project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from datetime import datetime
from time import gmtime, strftime

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pwvk1gmomfn!b_4h3ytp#drl0_!4p3tmi6+7kcrz_5-udd01)9'
# SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'


# ALLOWED_HOSTS = []
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    "drf_yasg",
    'key_images_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'key_images_app.auth.middleware.googleauthmiddleware.GoogleAuthMiddleware',
]


ROOT_URLCONF = 'key_images_back.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'key_images_back.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.getenv('DB_TEST_NAME', 'testdb'),
            'USER': os.getenv('DB_TEST_USERNAME', 'postgres'),
            'PASSWORD': os.getenv('DB_TEST_PASSWORD', 'test$test123'),
            'HOST': os.getenv('DB_TEST_HOSTNAME', 'localhost'),
            'PORT': os.getenv('DB_TEST_PORT', 9544)
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.getenv('DB_NAME', 'keyimagesdb'),
            'USER': os.getenv('DB_USERNAME', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'admin'),
            'HOST': os.getenv('DB_HOSTNAME', 'localhost'),
            'PORT': os.getenv('DB_PORT', 5432)
        }
    }

DATABASE_ROUTERS = ['key_images_app.tenants.dbrouter.DbRouter']


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

REST_FRAMEWORK = { 
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
    'UNAUTHENTICATED_USER': None,
}

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv('TIME_ZONE', 'America/Bogota')

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TENANT_BASE_URL = os.getenv('TENANT_BASE_URL', 'http://localhost:9009')

# tenant resources
USER_CUSTOM_RESOURCES = os.getenv('USER_CUSTOM_RESOURCES', False)
if USER_CUSTOM_RESOURCES:
    resources =  os.getenv('TENANT_RESOURCES', 'keyimages_db1, keyimages_db2').split(",")
    TENANT_RESOURCES = [s.strip() for s in resources]
else:
    TENANT_RESOURCES = []

# update resources on application start
UPDATE_RES_ON_START = os.getenv('UPDATE_RES_ON_START', 'True') == 'True'

# chek authorization token
JWT_AUTH_ENABLED = os.getenv('JWT_AUTH_ENABLED', 'False') == 'True'
# token source: header or cookie
JWT_TOKEN_SOURCE = os.getenv('JWT_TOKEN_SOURCE', 'cookie:testga')

# only accepts request from registered tenants
ONLY_REG_TENANTS_REQUESTS = os.getenv('ONLY_REG_TENANTS_REQUESTS', 'False') == 'True'

RESOURCE_TYPE = os.getenv('RESOURCE_TYPE', 'keyimagesdb')

# Name of tenat id variable
NAME_VARIABLE_TENANT_GOOGLE = os.getenv('NAME_VARIABLE_TENANT_GOOGLE', 'tenant')

# time to update resources 
RESOURCES_REFRESH_TIME = int( os.getenv('RESOURCES_REFRESH_TIME', 30) )


# are we in a testing environment?
if 'test' in sys.argv:
    # desable update of resources on start
    UPDATE_RES_ON_START = False
    # disable periodic update
    RESOURCES_REFRESH_TIME = 0


# lewvels -> DEBUG INFO WARNING ERROR CRITICAL
DJANGO_LOG_LEVEL = os.getenv('DJANGO_LOG_LEVEL', 'DEBUG')
DJANGO_LOG_FILE = os.getenv('DJANGO_LOG_FILE', 'logs.log.jsonl')

# v2
LOGGING = {
    'version': 1,
    # The version number of our log
    'disable_existing_loggers': False,
    "formatters": {
        "simple": {
            "format": "%(asctime)s | %(levelname)s | %(message)s",
            "datefmt": strftime("%Y-%m-%d %H:%M:%S +0000", gmtime()),
            "encoding": 'utf-8',
        },
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "format": "%(asctime)s %(levelname)s %(message)s",
            "datefmt": strftime("%Y-%m-%d %H:%M:%S +0000", gmtime()),
        }
    },
    'handlers': {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        'file': {
            'level': DJANGO_LOG_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            "formatter": "json",
            'filename': BASE_DIR / DJANGO_LOG_FILE,
            "backupCount": 5,
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
        },
    },
    'loggers': {
       "": {
            "handlers": ["console", "file"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
    },
}
